### ISSUE TITLE
cmake find_package not working with pre release versions

### ISSUE THREAD

**Issue by sburke56** [google/protobuf#1777]
This seems to be related to this pull request that was merged in.  
https://github.com/google/protobuf/pull/1624

I'm trying to run on Windows7 with VS 14.0 (Visual Studio 2015). CMake is 3.6.0-rc4. 

```
Could not find a configuration file for package "Protobuf" that exactly
matches requested version "3.0.0".

The following configuration files were considered but not accepted:

  D:/Users/sburke/sandbox/test/Source/Libs/3rdparty/protobuf-install/cmake/protobuf-config.cmake, version: 3.0.0-beta-3 (32bit)
```

My CmakeLists.txt file

```
cmake_minimum_required(VERSION 2.8.12)
set(Protobuf_DIR ${PROJECT_SOURCE_DIR}/Source/Libs/3rdparty/protobuf-install/cmake)

set(Protobuf_FIND_VERSION_PRERELEASE beta-3)
find_package(protobuf 3.0.0 EXACT CONFIG REQUIRED)

```

**Comment by podsvirov** [comment]
Try this code:
```CMake
find_package(Protobuf 3.0.0 EXACT CONFIG REQUIRED) # With capital "P"
```
Use one prefix everywhere.

**Comment by sburke56** [comment]
No dice.  Copying & pasting my file & output. 
```
cmake_minimum_required(VERSION 2.8.12)
set(Protobuf_DIR ${PROJECT_SOURCE_DIR}/Source/Libs/3rdparty/protobuf-install/cmake)

set(Protobuf_FIND_VERSION_PRERELEASE beta-3)
find_package(Protobuf 3.0.0 EXACT CONFIG REQUIRED)
```

Output error. 
```
  Could not find a configuration file for package "Protobuf" that exactly
  matches requested version "3.0.0".

  The following configuration files were considered but not accepted:

    D:/Users/sburke/sandbox/test/Source/Libs/3rdparty/protobuf-install/cmake/protobuf-config.cmake, version: 3.0.0-beta-3 (32bit)
```

**Comment by podsvirov** [comment]
@yeswalrus, any ideas?

**Comment by yeswalrus** [comment]
On it...

**Comment by sburke56** [comment]
Thanks it would make my life a little easier atm.

On Tue, Jul 12, 2016 at 5:32 PM, Walter Gray <notifications@github.com>
wrote:

> On it...
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/google/protobuf/issues/1777#issuecomment-232188066>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AANL47WeyCAVGG6Pp7A4rpLq88AOyUJYks5qVAfygaJpZM4JKs0n>
> .
>



-- 
Steve
www.stayathomedevs.com
GDEOnline.solutions
Game Data Editor Unity Plugin
<https://www.assetstore.unity3d.com/en/#!/content/18480>

**Comment by yeswalrus** [comment]
Resolved in https://github.com/google/protobuf/pull/1778. Sorry about that guys!

**Comment by sburke56** [comment]
This fix is not working for me.  I ran cmake again for protobufs & built with nmake and nmake install.  My resulting protobuf-config-version.cmake looks to have the fix.   Another question, it mentions it's looking for 32bit version of the protobuf package.  How do I build the 64 bit versions via nmake? 

Here's my error again and my protobuf-config-version.cmake file.
```
  Could not find a configuration file for package "Protobuf" that exactly
  matches requested version "3.0.0".

  The following configuration files were considered but not accepted:

    D:/Users/sburke/sandbox/ContentSDK/Source/Libs/3rdparty/protobuf-install/cmake/protobuf-config.cmake, version: 3.0.0-beta-3 (32bit)
```

protobuf-config-version.cmake 
```
# Prerelease versions cannot be passed in directly via the find_package command,
# so we allow users to specify it in a variable
if(NOT DEFINED "${PACKAGE_FIND_NAME}_FIND_VERSION_PRERELEASE")
  set("${${PACKAGE_FIND_NAME}_FIND_VERSION_PRERELEASE}" "")
else()
  set(PACKAGE_FIND_VERSION ${PACKAGE_FIND_VERSION}-${${PACKAGE_FIND_NAME}_FIND_VERSION_PRERELEASE})
endif()
```

**Comment by podsvirov** [comment]
@sburke56, for build 64 bit version start cmake and  nmake from appropriate x64 command prompt

**Comment by chunge11996** [comment]
nice!!

**Comment by sburke56** [comment]
This is still not working for me.  Any idea how I can help debug this?   I missed a question before about what version I was building.  I pulled the latest as of Jul 14. 

commit 10a8fb4e73b3dada58123aeabc393288ac791dc8
Author: Jon Skeet <skeet@pobox.com>
Date:   Thu Jul 14 22:01:47 2016 +0100

**Comment by yeswalrus** [comment]
@sburke56 From your last comment, it looks like the issue now is that you're trying to mix a 32 bit build of protobuf with a 64 bit app. See [CMAKE_SIZEOF_VOID_P](https://cmake.org/cmake/help/v3.5/variable/CMAKE_SIZEOF_VOID_P.html?highlight=sizeof_void_p#variable:CMAKE_SIZEOF_VOID_P)
or [Take a look at Stack Overflow](http://lmsotfy.com/?q=cmake+build+x64+nmake)

**Comment by sburke56** [comment]
I was able to build correctly with a x64 console.  I simply had a brain freeze about how to build it properly.  Now that the 3.0 release is out I'll have to try this again soon.
