### ISSUE TITLE
Python build failure on Windows x64

### ISSUE THREAD

**Issue by dhirschfeld** [google/protobuf#975]
Python 3
Windows 10 x64
VS 2015

```
C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\BIN\amd64\cl.exe /c /nologo /Ox /MD /W3 /GS- /DNDEBUG -I. -I../src -IC:\Anaconda3\envs\_build\include -IC:\Anaconda3\envs\_build\include /Tpgoogle/protobuf/pyext\scalar_map_container.cc /Fobuild\temp.win-amd64-3.4\Release\google/protobuf/pyext\scalar_map_container.obj /EHsc
scalar_map_container.cc
google/protobuf/pyext\scalar_map_container.cc(178): warning C4267: 'initializing': conversion from 'size_t' to 'int', possible loss of data
google/protobuf/pyext\scalar_map_container.cc(221): warning C4267: 'initializing': conversion from 'size_t' to 'int', possible loss of data
google/protobuf/pyext\scalar_map_container.cc(247): warning C4267: 'initializing': conversion from 'size_t' to 'int', possible loss of data
google/protobuf/pyext\scalar_map_container.cc(256): warning C4267: 'argument': conversion from 'size_t' to 'int', possible loss of data
google/protobuf/pyext\scalar_map_container.cc(308): warning C4267: 'argument': conversion from 'size_t' to 'int', possible loss of data
google/protobuf/pyext\scalar_map_container.cc(348): warning C4267: 'initializing': conversion from 'size_t' to 'int', possible loss of data
creating build\lib.win-amd64-3.4
creating build\lib.win-amd64-3.4\google
creating build\lib.win-amd64-3.4\google\protobuf
creating build\lib.win-amd64-3.4\google\protobuf\pyext
C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\BIN\amd64\link.exe /DLL /nologo /INCREMENTAL:NO /LIBPATH:C:\Anaconda3\conda-bld\work\cmake\Release /LIBPATH:C:\Anaconda3\envs\_build\libs /LIBPATH:C:\Anaconda3\envs\_build\PCbuild\amd64 libprotobuf.lib /EXPORT:PyInit__message build\temp.win-amd64-3.4\Release\google/protobuf/pyext\descriptor.obj build\temp.win-amd64-3.4\Release\google/protobuf/pyext\descriptor_containers.obj build\temp.win-amd64-3.4\Release\google/protobuf/pyext\descriptor_pool.obj build\temp.win-amd64-3.4\Release\google/protobuf/pyext\extension_dict.obj build\temp.win-amd64-3.4\Release\google/protobuf/pyext\message.obj build\temp.win-amd64-3.4\Release\google/protobuf/pyext\message_map_container.obj build\temp.win-amd64-3.4\Release\google/protobuf/pyext\repeated_composite_container.obj build\temp.win-amd64-3.4\Release\google/protobuf/pyext\repeated_scalar_container.obj build\temp.win-amd64-3.4\Release\google/protobuf/pyext\scalar_map_container.obj /OUT:build\lib.win-amd64-3.4\google\protobuf\pyext\_message.pyd /IMPLIB:build\temp.win-amd64-3.4\Release\google/protobuf/pyext\_message.lib /MANIFESTFILE:build\temp.win-amd64-3.4\Release\google/protobuf/pyext\_message.pyd.manifest
message.obj : warning LNK4197: export 'PyInit__message' specified multiple times; using first specification
   Creating library build\temp.win-amd64-3.4\Release\google/protobuf/pyext\_message.lib and object build\temp.win-amd64-3.4\Release\google/protobuf/pyext\_message.exp
descriptor.obj : error LNK2019: unresolved external symbol "private: static int google::protobuf::io::CodedInputStream::default_recursion_limit_" (?default_recursion_limit_@CodedInputStream@io@protobuf@google@@0HA) referenced in function "struct _object * __cdecl google::protobuf::python::GetOrBuildOptions<class google::protobuf::Descriptor>(class google::protobuf::Descriptor const *)" (??$GetOrBuildOptions@VDescriptor@protobuf@google@@@python@protobuf@google@@YAPEAU_object@@PEBVDescriptor@12@@Z)
message.obj : error LNK2001: unresolved external symbol "private: static int google::protobuf::io::CodedInputStream::default_recursion_limit_" (?default_recursion_limit_@CodedInputStream@io@protobuf@google@@0HA)
descriptor.obj : error LNK2019: unresolved external symbol "private: static enum google::protobuf::FieldDescriptor::CppType const * const google::protobuf::FieldDescriptor::kTypeToCppTypeMap" (?kTypeToCppTypeMap@FieldDescriptor@protobuf@google@@0QBW4CppType@123@B) referenced in function "class google::protobuf::FieldDescriptor const * __cdecl google::protobuf::python::field_descriptor::_GetDescriptor(struct google::protobuf::python::PyBaseDescriptor *)" (?_GetDescriptor@field_descriptor@python@protobuf@google@@YAPEBVFieldDescriptor@34@PEAUPyBaseDescriptor@234@@Z)
extension_dict.obj : error LNK2001: unresolved external symbol "private: static enum google::protobuf::FieldDescriptor::CppType const * const google::protobuf::FieldDescriptor::kTypeToCppTypeMap" (?kTypeToCppTypeMap@FieldDescriptor@protobuf@google@@0QBW4CppType@123@B)
message.obj : error LNK2001: unresolved external symbol "private: static enum google::protobuf::FieldDescriptor::CppType const * const google::protobuf::FieldDescriptor::kTypeToCppTypeMap" (?kTypeToCppTypeMap@FieldDescriptor@protobuf@google@@0QBW4CppType@123@B)
repeated_scalar_container.obj : error LNK2001: unresolved external symbol "private: static enum google::protobuf::FieldDescriptor::CppType const * const google::protobuf::FieldDescriptor::kTypeToCppTypeMap" (?kTypeToCppTypeMap@FieldDescriptor@protobuf@google@@0QBW4CppType@123@B)
descriptor_pool.obj : error LNK2019: unresolved external symbol "class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > const * const google::protobuf::internal::empty_string_" (?empty_string_@internal@protobuf@google@@3PEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@EB) referenced in function "class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > const & __cdecl google::protobuf::internal::GetEmptyStringAlreadyInited(void)" (?GetEmptyStringAlreadyInited@internal@protobuf@google@@YAAEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@XZ)
repeated_scalar_container.obj : error LNK2001: unresolved external symbol "int __cdecl google::protobuf::internal::Barrier_AtomicIncrement(int volatile *,int)" (?Barrier_AtomicIncrement@internal@protobuf@google@@YAHPECHH@Z)
scalar_map_container.obj : error LNK2001: unresolved external symbol "int __cdecl google::protobuf::internal::Barrier_AtomicIncrement(int volatile *,int)" (?Barrier_AtomicIncrement@internal@protobuf@google@@YAHPECHH@Z)
extension_dict.obj : error LNK2001: unresolved external symbol "int __cdecl google::protobuf::internal::Barrier_AtomicIncrement(int volatile *,int)" (?Barrier_AtomicIncrement@internal@protobuf@google@@YAHPECHH@Z)
message.obj : error LNK2001: unresolved external symbol "int __cdecl google::protobuf::internal::Barrier_AtomicIncrement(int volatile *,int)" (?Barrier_AtomicIncrement@internal@protobuf@google@@YAHPECHH@Z)
message_map_container.obj : error LNK2001: unresolved external symbol "int __cdecl google::protobuf::internal::Barrier_AtomicIncrement(int volatile *,int)" (?Barrier_AtomicIncrement@internal@protobuf@google@@YAHPECHH@Z)
repeated_composite_container.obj : error LNK2001: unresolved external symbol "int __cdecl google::protobuf::internal::Barrier_AtomicIncrement(int volatile *,int)" (?Barrier_AtomicIncrement@internal@protobuf@google@@YAHPECHH@Z)
build\lib.win-amd64-3.4\google\protobuf\pyext\_message.pyd : fatal error LNK1120: 4 unresolved externals
error: command 'C:\\Program Files (x86)\\Microsoft Visual Studio 14.0\\VC\\BIN\\amd64\\link.exe' failed with exit status 1120
```

https://groups.google.com/forum/m/#!topic/protobuf/9PwBzD038jI

**Comment by dhirschfeld** [comment]
It also fails for me with VS2013

**Comment by dhirschfeld** [comment]
...and fails with Python 2.7 as well

**Comment by dhirschfeld** [comment]
@jskeet - did you mean to reference this issue? I tried rebuilding with the latest master but still get the same unresolved externals error

**Comment by jskeet** [comment]
@dhirschfeld: Nope - that should have been issue 974. I've fixed the comment in question now, although I don't know whether that change will reflected here.

**Comment by xfxyjwf** [comment]
Python C++ implementation is not well supported (we actually haven't tested it on windows before). From your error message, it seems you haven't linked the protobuf lib when compiling the Python C++ extension. Adding protobuf lib to the linked libs should resolve most of the linker errors. I'm not sure it can solve all the problems though.

**Comment by dhirschfeld** [comment]
`libprotobuf.lib` is in the link line along with  `/LIBPATH:C:\Anaconda3\conda-bld\work\cmake\Release` which is the correct dir as can be seen below so AFAICS it is correctly linked?
```
λ ls

    Directory: C:\Anaconda3\conda-bld\work\cmake\Release

Mode                LastWriteTime         Length Name
----                -------------         ------ ----
-a----       26/11/2015     14:43        2107392 libprotobuf.dll
-a----       26/11/2015     14:43        1718645 libprotobuf.exp
-a----       26/11/2015     14:43        2791502 libprotobuf.lib
-a----       26/11/2015     14:46        1502720 libprotoc.dll
-a----       26/11/2015     14:46         113873 libprotoc.exp
-a----       26/11/2015     14:46         187018 libprotoc.lib
-a----       26/11/2015     14:46          17408 protoc.exe
```

Full link line:
```
C:\Program Files (x86)\Microsoft Visual Studio 12.0\VC\BIN\amd64\link.exe /DLL /nologo /INCREMENTAL:NO /LIBPATH:C:\Anaconda3\conda-bld\work\cmake\Release /LIBPATH:C:\Anaconda3\envs\_build\libs /LIBPATH:C:\Anaconda3\envs\_build\PCbuild\amd64 libprotobuf.lib /EXPORT:PyInit__message build\temp.win-amd64-3.4\Release\google/protobuf/pyext\descriptor.obj build\temp.win-amd64-3.4\Release\google/protobuf/pyext\descriptor_containers.obj build\temp.win-amd64-3.4\Release\google/protobuf/pyext\descriptor_pool.obj build\temp.win-amd64-3.4\Release\google/protobuf/pyext\extension_dict.obj build\temp.win-amd64-3.4\Release\google/protobuf/pyext\message.obj build\temp.win-amd64-3.4\Release\google/protobuf/pyext\message_map_container.obj build\temp.win-amd64-3.4\Release\google/protobuf/pyext\repeated_composite_container.obj build\temp.win-amd64-3.4\Release\google/protobuf/pyext\repeated_scalar_container.obj build\temp.win-amd64-3.4\Release\google/protobuf/pyext\scalar_map_container.obj /OUT:build\lib.win-amd64-3.4\google\protobuf\pyext\_message.pyd /IMPLIB:build\temp.win-amd64-3.4\Release\google/protobuf/pyext\_message.lib /MANIFESTFILE:build\temp.win-amd64-3.4\Release\google/protobuf/pyext\_message.pyd.manifest
```

**Comment by dhirschfeld** [comment]
The Python backend is too slow for my usecase so I was hoping to be able to compile the cpp backend. Unfortunately, I'm a bit stumped since AFAICS I am linking correctly but am still getting unresolved externals errors.

**Comment by dhirschfeld** [comment]
FWIW building the cpp backend used to work for version [`3.0.0a3.post418+g0cb84ee`](https://github.com/google/protobuf/tree/0cb84ee31fc2ac6e6f07c76a5dc20a20272d7516)

**Comment by xfxyjwf** [comment]
@dhirschfeld have you been able to find out what caused the python cpp build failure on windows?

**Comment by dhirschfeld** [comment]
I've not had time to track down the problem but will hopefully find some time this coming weekend to have a look...

**Comment by Suinga** [comment]
@dhirschfeld: Hello, I have a similar issue. Could you please tell me how to fix it? Thanks a lot.

**Comment by HelWord** [comment]
@dhirschfeld Hello, I have a similar issue when i built a Qt program with msvc2013_64.Could you please tell me how to fix it? Thanks a lot.

**Comment by dhirschfeld** [comment]
Sorry, I'm not sure how to fix it and haven't looked at it since.

**Comment by TeBoring** [comment]
I think this is obsolete. Right now we can build python wheel on windows.
